---
#
# Be aware that even a small syntax error here can lead to failures in output.
#
# Settings
mainfont: lmsans10-regular.otf
fontsize: 10pt
lang: en-us
geometry: a4paper, left=35mm, right=35mm, top=51mm, bottom=17mm

# Site
repository: dionisiskon/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dionisis Kontozidis
title: Graduate Student
email: p16kont@ionio.gr
website: dionisiskon.github.io/onlinecv
CV: shorturl.at/hv038

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: p16kont
github_username:  dionisiskon
facebook_username: dionisiskon1
instagram_username: dionisiskon

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/32637139.jpeg
about_content: | # this will include new lines to allow paragraphs 
 Hello, I'm a graduate student at Ionian University. I have developed basic skills in a number of programming languages, particularly Python, through my years studying and by some experimentation in my spare time.
 I'm currently creating apps using Kodular, because of it's simplicity and appealness in creating mobile apps, and trying to get my masters degree as a whole. I have quite an interest in web scraping technology and I'm currently trying to integrate machine learning to make it faster and more self-reliant.
  
  I am most skilled in: <mark>Python</mark> 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Novel Reader 
        # link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
         # - title:  dionisiskon/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/dionisiskon/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
         # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         I have started this project as a homework for a class but I really like it and want to improve upon it in the near future. It uses web scraping technology and is created through the <mark>Kodular</mark> platform.
         It pulls data from three of my favourite light/web novel websites and shows their content in an orderly manner. It was constructed, because of the problems I experienced with all the light novels apps I tested. 
      - layout: left  
        title: Forest Tale
        description: |
          This was also an assignment for university. It is a 2D platform game created using Unity and free forest assets available on the marketstore. Although it is short and simple, it is great fun!
      - layout: left
        title: FBCTF 
        description: | 
          It is a CTF created with the purpose of teaching about cybersecurity to students, constructed with the help of Facebook CTF platform. It uses Vagrant as a deployable environment and includes a lot of different challenges. It also includes a server(OVA file) for some challenges. 
       
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ionian University
        caption: 2016 - 2021
        sub_title: BSc Computer Science
        quote: >
          The Ionian University was founded in 1984, the same year as the University of Thessaly and the University of the Aegean. The university comprises of five faculties and twelve departments. Its seat is in Corfu, with university units in Lefkada, Kefalonia and Zakynthos.
        description: | # this will include new lines to allow paragraphs
           During my time in Ionian University I learnt some skills in a number of fields and also learned to work on deadlines. I additionally learnt how to co-operate doing projects by working on a team. 
           Last but not least, I enjoyed my time there, because it expanded my worldview as I was introduced to a great variety of subjects, that I found especially fascinating.
      - layout: left 
        title: Ionian University
        caption: 2022-Present
        sub_title: MSc in "Digital Applications and Innovation"
        quote: >
          The Postgraduate Program (MSc) in "Digital Applications and Innovation" of the Department of Informatics of the Ionian University aims to broaden the scientific skills of students in modern methodologies and technologies for the utilization of innovative applications in computer science and entrepreneurship.
        description: | 
          I just started so I don't have much to talk about my experience in the MSc. That said, I can say that I particularly enjoy the wide variety in subjects. It is fun that we have an assignment on mobile application using MIT App Inventor(and other platforms based on it) and we also focus on innovations. I can surely say that the previous experience in the same university, helped a lot in familiarizing with the environment in this (post)graduate program.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in web scraping and creating apps, some of my other interests and hobbies are:
      - Reading 
      - Chess
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: dionisiskon/modern-resume-theme@master

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
---
