name: Document Conversion

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: "-s -f markdown-auto_identifiers _config.yml -o cv.pdf --template=template.tex --pdf-engine=xelatex"
      - uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv.pdf
          
  deploy: # Deploy process 
    name: Deploy
    needs: convert_via_pandoc 
    # the build job must succeed in order to run this job
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2 
      # downloads the uploaded build files
      with:
        name: cv.pdf
        path: ./

    - name: [skip ci] Deploy to Github pages
      uses: crazy-max/ghaction-github-pages@v2
      # action to deploy to GitHub Pages
      with:
        target_branch: gh-pages
        build_dir: ./
        keep_history: true
      env:
        GH_PAT: ${{ secrets.TOKEN }} # default secret for auth
