name: Document Conversion

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: "-s -f markdown-auto_identifiers _config.yml -o cv.pdf --template=template.tex --pdf-engine=xelatex"
      - uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv.pdf
